version: '2'

services:
  app:
    image: 'user-service:latest'
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    container_name: app

    depends_on:
      - user_db
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "5005:5005"


  user_db:
    image: 'postgres:13.1-alpine'
    container_name: user_db
    env_file:
      - .env
    volumes:
      - ../src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - user-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  user-db-data: